name: "test pull request"

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  IMAGE_NAME: "simaofsilva/plex-meta-manager"
  TAG: "test"
  META_MANAGER_VERSION: "v1.15.1" # renovate: datasource=github-tags depName=meisnate12/Plex-Meta-Manager

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          load: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          build-args: |
            META_MANAGER_VERSION=${{ env.META_MANAGER_VERSION }}

      - name: Test image
        run: |
          docker run --rm ${{ env.IMAGE_NAME }}:${{ env.TAG }} --test
