name: build and push image

on:
  push:
    branches:
      - 'main'
    paths:
      - Dockerfile
      - .github/workflows/push.yml

env:
  IMAGE_NAME: "simaofsilva/plex-meta-manager"
  META_MANAGER_VERSION: "v1.17.3" # renovate: datasource=github-tags depName=meisnate12/Plex-Meta-Manager

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3    

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.META_MANAGER_VERSION }}
            ${{ env.IMAGE_NAME }}:latest
          file: Dockerfile
          build-args: META_MANAGER_VERSION=${{ env.META_MANAGER_VERSION }}

  delete_old_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.3
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 15
          keep_minimum_runs: 5
